version: "2.24.6"

services:
  
  postgre-compose:
    container_name: postgres-container
    image: postgres
    environment:
      hostname: ""
      POSTGRES_USER: ""
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"